### ISSUE TITLE
dataset 

### ISSUE THREAD

**Issue by Eggplantsjz** [PKU-IDEA/MacroRank#1]
Could you please provide information about each txt file in the dataset and the meaning of each line within the files? Thank you kindly.

**Comment by Constwelve** [comment]
I have included a file named `README_DATA.md` to provide additional explanations regarding the `.txt` files in the dataset.

**Comment by Eggplantsjz** [comment]
Thank you for resolving my  issue and providing a solution. I sincerely appreciate your assistance and the effort you put into addressing my problem.
